# Reference: https://osbuild.org/docs/user-guide/blueprint-reference/

# TODO: No support yet
# [customizations.services]
# enabled = ["microshift"]

[[customizations.disk.partitions]]
type = "lvm"
name = "mainvg"
minsize = "60 GiB"

[[customizations.disk.partitions.logical_volumes]]
lv_name = "rootlv"
minsize = "30 GiB"
fs_type = "ext4"
mountpoint = "/"

[[customizations.disk.partitions.logical_volumes]]
lv_name = "microshiftlv"
minsize = "30 GiB"
fs_type = "ext4"
mountpoint = ""

# TODO: No support yet
# [customizations.openscap]
# datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml"
# profile_id = "xccdf_org.ssgproject.content_profile_cis"
