# Reference: https://osbuild.org/docs/user-guide/blueprint-reference/

# Without `develop` user, the user `hp` cannot login
[[customizations.group]]
name = "develop"
gid = 1002
[[customizations.user]]
name = "develop"
description = "Dummy User for enabling sysuser creations"
# password = "password"
# groups = ["wheel"]
home = "/home/develop"
shell = "/sbin/nologin"
uid = 1002
gid = 1002

[[customizations.group]]
name = "gitlab-runner"
gid = 1003
[[customizations.user]]
name = "gitlab-runner"
description = "Pipeline Runner"
key = "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMH5Rhp5ttT2f/CpTkkKik1a/cOR6ias6FcEcniWfOKFDoGrDjOaml+SkpLhzCLy2M8Yl0Ft1vIQBo8YnQKuUm4= gitlab-runner@green.pamperspoil.com"
groups = ["wheel"]
home = "/home/gitlab-runner/"
shell = "/bin/bash"
uid = 1003
gid = 1003

[[customizations.files]]
path = "/etc/sudoers.d/90-gitlab-runner"
mode = "0440"
user = "root"
group = "root"
data = """
gitlab-runner ALL=(ALL) NOPASSWD:ALL
"""

# This user would not enable hp to login ... maybe home dir path?
# [[customizations.user]]
# name = "root"
# description = "Console Only Root"
# groups = ["wheel"]
# home = "/root"
# shell = "/bin/bash"

[[customizations.disk.partitions]]
type = "lvm"
name = "rhel"
minsize = "30 GiB"

[[customizations.disk.partitions.logical_volumes]]
lv_name = "root"
minsize = "30 GiB"
fs_type = "xfs"
mountpoint = "/"

[[customizations.disk.partitions.logical_volumes]]
lv_name = "microshift-placeholder"
minsize = "10 GiB"
fs_type = "xfs"
mountpoint = "/var/microshift"
