# Reference: https://osbuild.org/docs/user-guide/blueprint-reference/

# [[customizations.user]]
# name = "develop"
# description = "Development User"
# password = "password"
# groups = ["wheel"]
# home = "/home/develop"
# shell = "/bin/bash"

[[customizations.disk.partitions]]
type = "lvm"
name = "main-vg"
minsize = "10 GiB"

[[customizations.disk.partitions.logical_volumes]]
lv_name = "root-lv"
minsize = "30 GiB"
fs_type = "xfs"
mountpoint = "/"

[[customizations.disk.partitions.logical_volumes]]
lv_name = "microshift-lv"
minsize = "30 GiB"
fs_type = "xfs"
mountpoint = "/var/microshift"

