[[customizations.user]]
name = "hp"
key = "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEYWbHj1jB5tIlEevA9SgLVdtPsvkQbV+zAiuA4Dnsr3vFDW04bPLtayKfq9ltEqMvNV9O22vLzYnSaQ7PEKTXE= hp@t14s.pamperspoil.com"
groups = ["wheel"]

[[customizations.user]]
name = "hp"
key = "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLOFyezeUT9oLKLG7TMG98hnAqxaWaD0fiDqkZp+EW9vA9laXFeAn6kA6SZ6bfvwOeiitImDURXMxU1V+9XT+hE= hp@green.home"
groups = ["wheel"]
